# Generated by Django 5.0 on 2024-01-04 00:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.CharField(max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(default='')),
                ('content_images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
            ],
            options={
                'db_table': 'Articles',
            },
        ),
    ]
