# Generated by Django 5.0 on 2024-01-04 04:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None),
        ),
    ]
