# Generated by Django 5.0 on 2024-01-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_image_url', models.CharField(max_length=255)),
                ('project_title', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
            ],
            options={
                'db_table': 'Projects',
            },
        ),
    ]
